# Generated by Django 2.0.1 on 2018-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='URL short code'),
        ),
    ]
